### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by gdi2290** [pwnall/node-xhr2#18]
hi, we're evaluating your module to use for Universal Angular 2 but we ran into a small problem. With your module you require the url to have a protocol which means a full url. On the client this is not the case since we're able to use relative paths. Do you think we can support relative urls or did I overlook a feature? 

pending PR https://github.com/angular/universal/pull/73

**Comment by pwnall** [comment]
@gdi2290 I'm definitely interested in understanding what you need to make this work!

I'd need a base URL to interpret relative URLs to. Would you be providing a base URL via `nodeSet`?
https://github.com/pwnall/node-xhr2/blob/master/src/001-xml_http_request.coffee#L260

**Comment by pwnall** [comment]
@gdi2290 To be clear: there's no support for relative URLs yet. I'm willing to implement it, if we can agree on a useful API.

**Comment by gdi2290** [comment]
if you can expose a method to set a baseUrl I can find a way to pass it along. When the Universal App is ran we can assume either the user set the baseUrl on the server (for load balancing etc) or we can grab the baseUrl from the <base> tag (also needed for the router and probably rendered anyways from the server).

**Comment by pwnall** [comment]
Excellent, I just wanted to make sure we're on the same page for what needs to get implemented.

**Comment by gdi2290** [comment]
thanks! :+1:

**Comment by manekinekko** [comment]
Good news! Thx @pwnall :+1:

**Comment by pwnall** [comment]
Relative URL support added in 3eee46cfb8f4708eaf982b84fdf463dc1bed70b9

Please try out version 0.1.3, and let me know if that works for you. You set the base URL by calling

```
XMLHttpRequest.nodejsSet baseUrl: '.....'
```

You can also call `nodejsSet` on individual XHR objects, but that's pretty much useless after you call `open`.

**Comment by manekinekko** [comment]
LGTM
