### ISSUE TITLE
Non-automatic redirects

### ISSUE THREAD

**Issue by felixSchl** [pwnall/node-xhr2#26]
Is it possible at all to not automatically follow redirects?

**Comment by pwnall** [comment]
[This StackOverflow post](http://stackoverflow.com/questions/228225/prevent-redirection-of-xmlhttprequest) confirms my suspicion that the XHR spec does not include a way to modify the redirect behavior. Sorry!

If you need that level of control, you might need to use node's http API directly (or via the request library), or the newer [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch).
