### ISSUE TITLE
Support for custom User-Agent

### ISSUE THREAD

**Issue by Tobsic** [pwnall/node-xhr2#29]
Sometimes it is necessary to set a custom User-Agent header. I don't see any possibility to do so (`setRequestHeader` restricts to set it). It would be good to set it via global, option or `nodejsSet`.

**Comment by perry-mitchell** [comment]
As per [MDN docs](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name):

> The User-Agent header is no longer forbidden, [as per spec](https://fetch.spec.whatwg.org/#terminology-headers) — see forbidden header name list (this was implemented in Firefox 43) — it can now be set in a Fetch [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) object, or via XHR [setRequestHeader()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#setRequestHeader%28%29).

@pwnall Would you consider a PR to remove this restriction?

**Comment by pwnall** [comment]
Thank you very much for doing the research!

I'd love to see a PR that aligns this with the spec. The PR would need to change `headers_test.coffee` to verify that a user-specified `User-Agent` correctly overrides the default.

Separately, I agree that it'd make sense to move the default `User-Agent` value to a `@ nodejsUserAgent`, and have `nodejsSet` support for it. I'd be happy to review & merge such a PR.

**Comment by perry-mitchell** [comment]
Great! I'm no coffeescript expert but I'll give it a go. I'll definitely update the tests.

> move the default User-Agent value to a @ nodejsUserAgent, and have nodejsSet support for it

Might I ask why? If the User-Agent is now a configurable header, why not allow it to be set via the `setRequestHeader` method? Seeing as it can be set both in the browser and NodeJs..
