### ISSUE TITLE
Support synchronous function

### ISSUE THREAD

**Issue by BruceAn1978** [pwnall/node-xhr2#30]
The synchronous function is very useful for some scenes.

Is this function support now?

**Comment by pwnall** [comment]
Please look at #19 -- is this the same request?

**Comment by mdabdul330** [comment]
It looks like the same. Asynchronous do break the normal functionality and Synchrounous is not supported yet (in the latest version)

**Comment by pwnall** [comment]
Going to duplicate this against #19
