### ISSUE TITLE
Turn off keepalive or re-use existing connections.

### ISSUE THREAD

**Issue by ARitz-Cracker** [pwnall/node-xhr2#32]
Hey, something I use depends on this and I'm making, like, tens of thousands of http calls. Mind turning off keepalive so the OS doesn't freak out and run out of outgoing ports? Or if you want to put more effort, re-use existing connections?

**Comment by pwnall** [comment]
Can you set your own HTTP agent via XMLHttpRequest.nodejsSet?

API description:
https://github.com/pwnall/node-xhr2/blob/c22c61dadf754c805bcf37af08e8f908b8ce730a/src/001-xml_http_request.coffee#L244

node.js Agents:
https://nodejs.org/api/http.html#http_class_http_agent

**Comment by ARitz-Cracker** [comment]
Fair enough. Apologies for being a harsh. I'll submit a PR request to the repo I depend on so that things can be done properly.
